CREATE TABLE IF NOT EXISTS USER_LOGIN   --用户登录表
(
    USER_ID VARCHAR2(15) NOT NULL,       --用户账号
    USER_PASSWORD VARCHAR2(20) NOT NULL, --用户密码
    USER_TYPE CHAR(1) NOT NULL,          --用户类型 0：管理员，1：工作人员，2：访客
    USER_STATUS CHAR(1) NOT NULL,        --用户状态 0：正常，1：注销
    PRIMARY KEY(USER_ID)
);



CREATE TABLE IF NOT EXISTS USER_INFO    --用户信息表
(
    USER_ID VARCHAR2(15) NOT NULL,       --用户账号
    USER_NAME VARCHAR2(20),              --用户名称
    USER_GENDER CHAR(1) NOT NULL,        --用户性别 F：女性，M：男
    USER_PSPT_ID CHAR(18) NOT NULL,      --用户身份证号码
    USER_PHONE CHAR(11) NOT NULL,        --用户手机号
    USER_EMAIL VARCHAR2(30) ,            --用户邮箱
    PRIMARY KEY(USER_ID)
);


CREATE TABLE IF NOT EXISTS AUTHOR_INFO  --作者信息表
(
    AUTHOR_ID VARCHAR2(10) NOT NULL,     --作者编号
    AUTHOR_NAME VARCHAR2(50) NOT NULL,   --作者名称
    AUTHOR_STATUS CHAR(1) NOT NULL,      --作者信息状态 0：正常，1：失效
    PRIMARY KEY (AUTHOR_ID)
);


CREATE TABLE IF NOT EXISTS PRESS_INFO       --出版社信息表
(
    PRESS_ID VARCHAR2(10) NOT NULL,         --出版社编号
    PRESS_NAME VARCHAR2(50) NOT NULL,       --出版社名称
    PRESS_STATUS CHAR(1) NOT NULL,          --出版社信息状态 0：正常，1：失效
    PRIMARY KEY (PRESS_ID)
);


CREATE TABLE IF NOT EXISTS BOOK_TYPE_INFO   --图书类型信息表
(
    BOOK_TYPE_ID CHAR(1) NOT NULL,          --图书类型编号
    BOOK_TYPE_NAME VARCHAR2(50) NOT NULL,   --图书类型名称
    BOOK_TYPE_STATUS CHAR(1) NOT NULL,      --图书类型信息状态 0：正常，1：失效
    PRIMARY KEY (BOOK_TYPE_ID)
);


CREATE TABLE IF NOT EXISTS BOOK_INFO    --图书信息表
(
    BOOK_ID VARCHAR2(15) NOT NULL,       --图书编号（ISBN）
    BOOK_NAME VARCHAR2(50) NOT NULL,     --图书名称
    BOOK_TYPE_ID CHAR(1) NOT NULL,       --图书类型编号
    AUTHOR_ID VARCHAR2(10) NOT NULL,     --作者编号
    PRESS_ID VARCHAR2(10) NOT NULL,      --出版社编号
    BORROWED_NUMBER INT NOT NULL,        --借阅数量
    REMAINING_NUMBER INT NOT NULL,       --剩余数量
    BOOK_STATUS CHAR(1) NOT NULL,        --图书状态 0：正常，1：失效
    PRIMARY KEY (BOOK_ID),
    FOREIGN KEY (BOOK_TYPE_ID) REFERENCES BOOK_TYPE_INFO (BOOK_TYPE_ID),
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR_INFO (AUTHOR_ID),
    FOREIGN KEY (PRESS_ID) REFERENCES PRESS_INFO (PRESS_ID)
);


CREATE TABLE IF NOT EXISTS BORROWED_INFO    --借阅信息表
(
    BORROWED_ID VARCHAR2(15) NOT NULL,      --借阅编号
    USER_ID VARCHAR2(15) NOT NULL,          --用户账号
    BOOK_ID VARCHAR2(15) NOT NULL,          --图书编号（ISBN）
    BORROWED_NUMBER INT NOT NULL,           --借阅数量
    BORROWED_START_DATE DATE NOT NULL,      --借阅开始时间
    BORROWED_END_DATE DATE NOT NULL,        --借阅到期时间
    BORROWED_STATUS CHAR(1)  NOT NULL,      --借阅状态 0：正在借阅，1：借阅逾期，2，借阅结束
    PRIMARY KEY (BORROWED_ID)
);
